BHoM/BHoM_Adapter

- BHoM_Adapter/BHoMAdapter.cs
- BHoM_Adapter/BHoM_Adapter.csproj
- BHoM_Adapter/CRUD/Read.cs
- BHoM_Adapter/CRUD/Replace.cs
- BHoM_Adapter/CRUD/UpdateOnly.cs
- BHoM_Adapter/CRUD/UpdateProperty.cs
https://github.com/BHoM/BHoM/pull/509
Fixes #100 
N/A
- Changed `*.Query` to `*.Request` following changes in Data_oM
Do not merge until all dependent PRs are ready as well :smile:
> BHoM_Adapter: Update Query to Request from Data oM

- .github/ISSUE_TEMPLATE/api_changed.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compliance.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test_script.md
Added github templates in .github/ISSUE_TEMPLATE
Closes #104 
No test file needed.
> BHoM_Adapter: Implement Issue Templates on Repos

- File_Adapter/CRUD/Create.cs
- File_Adapter/CRUD/Delete.cs
- File_Adapter/CRUD/Read.cs
- File_Adapter/FileAdapter.cs
- File_Adapter/File_Adapter.csproj
Closes #111.
Good explanation of changes in the issue itself.
See issue.
I was tempted to remove also the default values in the File_Adapter constructor signature, as they seem rather specific and their presence is quite cryptic.
I didn't do that just because they seem something like that has (had?) a use but couldn't understand what. 
If someone has a better idea of what they're for, I'd prefer to add a comment to explain them.
> File_Adapter-issue111-minor refactor (extension if needed, param name)

- BHoM_Adapter/Properties/AssemblyInfo.cs
- File_Adapter/Properties/AssemblyInfo.cs
Closes #118 
Updates the `AssemblyFileVersion` to `2.3.0.0`
> BHoM_Adapter: Update Assembly File Version

- BHoM_Adapter/BHoMAdapter.cs
- BHoM_Adapter/BHoM_Adapter.csproj
- BHoM_Adapter/CRUD/Replace.cs
- BHoM_Adapter/CRUD/UpdateOnly.cs
- File_Adapter/CRUD/Create.cs
- File_Adapter/CRUD/Read.cs
#86 
#89 
https://github.com/BHoM/BHoM_Engine/pull/1092
Any script that does a Push - the more objects in the push, the better.
- Objects are now deep cloned at the start of the Push
- `ReplaceThroughApi()` has been simplified
> refactoring-Level1 changes

- BHoM_Adapter/BHoMAdapter.cs
https://github.com/BHoM/BHoM_UI/pull/133
Closes #91 
Closes #125 
https://burohappold.sharepoint.com/:f:/s/BHoM/EuLYM_Y59tNMkVjQSVhuo1cBXNxPclS8Ly7EmEzd3fRhHg?e=0UriL3
* Renamed Adapter method `PullTo` to `Move` to be consistent with UI naming
* Move method now accepts 2 config parameters: `pullConfig` and `pushConfig`
> Refactoring-level2

- File_Adapter/FileAdapter.cs
Closes #143 
https://burohappold.sharepoint.com/:u:/s/BHoM/ERekpoPskXFOuC66VS7yG74BFNT5HaGuqKBFTcOj_qRvfw?e=qCF92Q
> File_Adapter: If no fileName extension is specified, defaults to .json

- BHoM_Adapter/Properties/AssemblyInfo.cs
- File_Adapter/Properties/AssemblyInfo.cs
> Updated AssemblyVersion and AssemblyFileVersion to 3.0.0.0

- BHoM_Adapter/Properties/AssemblyInfo.cs
- File_Adapter/Properties/AssemblyInfo.cs
> Updated assembly version 

- .ci/run-compliance-tests.yml
> Update CI file

- Adapter_Engine/Adapter_Engine.csproj
> Fix reference to Diffing oM

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_Engine/Query/GetFullFileName.cs
- Adapter_oM/Adapter_oM.csproj
- Adapter_oM/FileSettings.cs
Closes #176 
Created a default file settings object that handles file name and directory. File path query which gets the full file path from the settings and is to be used with adapters.
> FileSettings object

- Adapter_oM/enums/PushType.cs
> Added description of PushTypes in the enum to be visible in UI's tooltip

- Structure_AdapterModule/Structure_AdapterModules.csproj
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
Closes #200 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary to comply with the changes.
> Update IElement references with the Dimensional_oM

- BHoM_Adapter/AdapterActions/_PushMethods/ExternalId/AssignId.cs
Closes #198
@kThorsager to test
> Added null check in AssignNextFreeId

- .ci/check-all-depandants.yml
- .ci/check-core.yml
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
> Update CI files

- Adapter_oM/Settings-Config/AdapterSettings.cs
- Adapter_oM/enums/PushType.cs
- BHoM_Adapter/AdapterActions/Push.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/UpdateOnly.cs
PR replacing the one with conflicting changes https://github.com/BHoM/BHoM_Adapter/pull/214
Closes #206 
Adding do-not-merge because it will ripple through to:
- Revit: https://github.com/BHoM/Revit_Toolkit/pull/608
- ETABS: https://github.com/BHoM/ETABS_Toolkit/pull/285
> Renamed PushType.FullCRUD to FullPush

- Adapter_Engine/Query/GetComparerForType.cs
- Adapter_oM/Adapter_oM.csproj
- Adapter_oM/Settings-Config/ActionConfig.cs
- File_Adapter/AdapterActions/Push.cs
- File_Adapter/FileAdapter.cs
https://github.com/BHoM/BHoM_Engine/pull/1534
https://github.com/BHoM/BHoM/pull/715
Closes https://github.com/BHoM/BHoM_Adapter/issues/217
> Align to Diffing Engine and oM changes

- Adapter_oM/Module/ModuleSet.cs
See https://github.com/BHoM/BHoM_Engine/pull/1743 and https://github.com/BHoM/BHoM_UI/pull/253 for more details
> Adapter_oM: Add a constructor from List for ModuleSet

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_oM/Adapter_oM.csproj
- BHoM_Adapter/BHoM_Adapter.csproj
- File_Adapter/File_Adapter.csproj
- Structure_AdapterModules/Structure_AdapterModules.csproj
Closes #231 
Closes #232 
Setting all copy locals to false, and correct folder for release builds
> All copy locals to false and correct build folder for Release

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_oM/Adapter_oM.csproj
- BHoM_Adapter/BHoM_Adapter.csproj
- File_Adapter/FileAdapter.cs
- File_Adapter/File_Adapter.csproj
- Structure_AdapterModules/Structure_AdapterModules.csproj
Not fully depending on, but related to:
https://github.com/BHoM/BHoM_Engine/issues/1822
Closes #234
Change default folder for the file-adapter to ProgramData
All in support of https://github.com/BHoM/admin/issues/5
> Update default filepath of the FileAdapter

- BHoM_Adapter/AdapterActions/Pull.cs
- BHoM_Adapter/AdapterActions/_PullMethods/ReadResults.cs
- BHoM_Adapter/BHoM_Adapter.csproj
- BHoM_Adapter/CRUD/IRead.cs
https://github.com/BHoM/BHoM/pull/911
Aligning with migration of Results from Common_oM to Analytical_oM.
Also, removing reference to Common_oM as no longer needed.
> Aligning with changes migrating Results to Analytical_oM

- Adapter_Engine/Properties/AssemblyInfo.cs
- Adapter_oM/Properties/AssemblyInfo.cs
- Adapter_oM/enums/PushType.cs
- BHoM_Adapter/AdapterActions/Push.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
- BHoM_Adapter/Properties/AssemblyInfo.cs
- File_Adapter/Properties/AssemblyInfo.cs
- Structure_AdapterModules/Properties/AssemblyInfo.cs
Closes #242 
https://github.com/BuroHappoldEngineering/Filing_Toolkit/pull/48
> Adapter_oM: Added `CreateOrUpdate` to the `PushTypes` 

- BHoM_Adapter/AdapterActions/Pull.cs
- BHoM_Adapter/AdapterActions/_PullMethods/ReadResults.cs
- Structure_AdapterModules/ErrorMessages/ErrorMessages.cs
- Structure_AdapterModules/Structure_AdapterModules.csproj
Closes #240
Removes methods supporting pulling results using FIlterRequests
This will be a braking change for multiple structural adapters, to be merged together with those.
> Remove support for pulling results with filter request

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_Engine/Query/AdapterId.cs
- Adapter_Engine/Query/AdapterIds.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
- BHoM_Adapter/CRUD/IDelete.cs
- BHoM_Adapter/CRUD/IUpdate.cs
- BHoM_Adapter/HelperMethods/CopyBHoMObjectProperties.cs
PR replacing https://github.com/BHoM/BHoM_Adapter/pull/287 due to merge conflicts. 
See full description, commits and comments on https://github.com/BHoM/BHoM_Adapter/pull/287.
Closes #284
Closes #288
Needs testing of existing functionality on all Adapters.
> Adapter_Engine: Avoid signature duplication for AdapterId() methods

- Adapter_Engine/Modify/SetAdapterId.cs
- Adapter_Engine/Query/AdapterIds.cs
- Adapter_Engine/Query/GetFullFileName.cs
- Adapter_Engine/Query/HasAdapterIdFragment.cs
> Handle nulls in Adapter_Engine methods

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_Engine/Create/BHoMAdapter.cs
Closes #300
Adding method for creating an adapter based on a type via reflection.
Useful for creation of adapters dynamically from the code side and also have some use from excel vba workflows as well as testscripts in grasshopper.
Will be required for automatic interop testing by the BHoMBot.
https://burohappold.sharepoint.com/:f:/s/BHoM/Emk-_8egMhhDpHySuegqFAEBLUoH3DJu4lq-RcG6-CRYJg?e=psemXO
> Adding method to create adapter from Type

- Adapter_oM/Adapter_oM.csproj
- Adapter_oM/ExecuteCommands/Exit.cs
Closes #302
Adding new command for fully closing down linked open instance of the software.
https://burohappold.sharepoint.com/:f:/s/BHoM/EjpTgU6jo_tJr30rbJs0a_gBnZnhI1rYcv3aQ-Yc3A6E2g?e=fenJ0J
> Add Exit Command

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_Engine/Create/BHoMAdapter.cs
- Adapter_Engine/Modify/SetAdapterId.cs
- Adapter_Engine/Query/AdapterId.cs
- Adapter_Engine/Query/AdapterIds.cs
- Adapter_Engine/Query/AdapterMethods.cs
- Adapter_Engine/Query/GetComparerForType.cs
- Adapter_Engine/Query/GetDependencyObjects.cs
- Adapter_Engine/Query/GetDependencyTypes.cs
- Adapter_Engine/Query/GetFullFileName.cs
- Adapter_Engine/Query/HasAdapterIdFragment.cs
- Adapter_oM/Adapter_oM.csproj
- Adapter_oM/IBHoMAdapter.cs
- BHoM_Adapter/AdapterActions/Execute.cs
- BHoM_Adapter/AdapterActions/Push.cs
- BHoM_Adapter/AdapterActions/_PullMethods/ReadResults.cs
- BHoM_Adapter/AdapterActions/_PushMethods/AdapterId/NextFreeId.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/CreateOnly.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
- BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/UpdateOnly.cs
- BHoM_Adapter/AdapterActions/_PushMethods/ProcessObjectsForPush.cs
- BHoM_Adapter/AdapterActions/_PushMethods/Support/UpdateTag.cs
- BHoM_Adapter/BHoMAdapter.cs
- BHoM_Adapter/BHoM_Adapter.csproj
- BHoM_Adapter/CRUD/IDelete.cs
- BHoM_Adapter/CRUD/IRead.cs
- BHoM_Adapter/CRUD/IUpdate.cs
- BHoM_Adapter/HelperMethods/AdapterId.cs
- BHoM_Adapter/HelperMethods/CopyBHoMObjectProperties.cs
- Structure_AdapterModules/ErrorMessages/ErrorMessages.cs
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729
> Align with changes in oM and Engine on Reflection -> Base

- Adapter_Engine/Adapter_Engine.csproj
- Adapter_oM/Adapter_oM.csproj
- BHoM_Adapter/BHoM_Adapter.csproj
- Structure_AdapterModules/Structure_AdapterModules.csproj
Update Assembly Information to include description
> Update Assembly Information

- Adapter_oM/ExecuteCommands/CustomCommand.cs
- Adapter_oM/Settings-Config/AdapterSettings.cs
Closes #363
Simply adding getters and setters, ensuring all fields are properties
> Add getters and setters to make fields into properties

- .ci/BHoMBot/Nuget/BHoM.Adapter.nuspec
> Add nuspec template file

- .ci/BHoMBot/Nuget/BHoM.Adapter.nuspec
> Fix spelling for nuspec template

- .ci/unit-tests/BHoM_Adapter_Tests/BHoM_Adapter_Tests.csproj
- Adapter_Engine/Adapter_Engine.csproj
- Adapter_oM/Adapter_oM.csproj
- BHoM_Adapter/BHoM_Adapter.csproj
- Structure_AdapterModules/Structure_AdapterModules.csproj
Update AssemblyFileVersion to 7.3
Remove previous version attributes
> Update AssemblyFileVersion to 7.3
