BHoM/BHoM_Adapter

BHoM_Adapter/BHoM_Adapter.csproj, BHoM_Adapter/HelperMethods/MapSpecialProperties.cs
https://github.com/BHoM/BHoM/pull/481
Closes #81 
Adding reference to Analytical_oM
Done in parallel to Structure_oM sprint, but this could be merged before as only change made is updating references
**EDIT** now depends on BHoM change for the Node class
Could be discussed if these dependencies should exist at all, but as current adapter has a dependecy on Structure_oM due to "MapSpecialProperties" method, the dependencies needs to be updated.
Removing these dependencies can be done as a separate sprint if wanted.
=> Adding reference to Analytical_oM

BHoM_Adapter/CRUD/Replace.cs
Closes #102 
If no tag is provided and if no comparer is provided, reading in existing data is unnecessary, as this mean non of the comparison methods will be able to do anything.
Adding check for this in Replace method
Test that any push methods are working as before.
I have been runnig on this code for quite some time and have not experienced any problems. SHould give a speedup pushing elements without comparers to models already containing data. For example pushing panels to a Robot model already containing a large set of panels.
=> BHoM_Adapter - Adding check as to whether a read in necessary in Replace method

File_Adapter/CRUD/Pull.cs, File_Adapter/FileAdapter.cs, File_Adapter/File_Adapter.csproj
Fixes #121 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Adapter/File_Adapter-Issue121/Data%20Set%20Creation.gh?csf=1&e=E7VzLK) - This will create a dataset. If the bug is fixed, it will create it first time. If the bug persists, it will fail on the first push (pushing an empty file) and then succeed the second time. The latter behaviour is incorrect.
- Fixed File_Adapter bug for pushing new files which don't exist yet
=> File_Adapter: Fix file adapter bug

BHoM_Adapter/BHoM_Adapter.csproj, BHoM_Adapter/Properties/AssemblyInfo.cs, File_Adapter/File_Adapter.csproj, File_Adapter/Properties/AssemblyInfo.cs
Closes https://github.com/BHoM/BHoM_Adapter/issues/132
* Update AssemblyFileVersion to 2.4.0.0
* Set CopyLocal to False
=> BHoM_Adapter: Update AssemblyFileVersion, set CopyLocal to false

BHoM_Adapter/CRUD/Replace.cs
Closes #134 
When replacing a dependent object, the `AdapterId `was not mapped to all the `dependencyObjects`, this is because a distinct list of the original objects (`newObjects`) was used to determine the dependency objects- rather than the complete list of `objectsToPush`. This is rectified by using `objectsToPush `to determine the `dependencyObjects`, hence the mapping of the `AdapterId `to the `dependencyObjects `applies to all of them, not just those that were determine from the distinct list of `objectsToPush`.
https://burohappold.sharepoint.com/:f:/s/BHoM/ErcnwvYD2WFPhxygE9UQEQUBKf5ZCE8qwwB1UB8lObNieA?e=6yYoE6
Fixed a bug where `AdapterId `was not being mapped to all `dependencyObjects `causing an error when pushing objects with dependencies. 
See Additional Comments in  #134
=> BHoM_Adapter: Mapping of IDs to dependencyObjects 

BHoM_Adapter/AdapterActions/Pull.cs
Closes #165 
Casting adapter as dynamic before Read and ReadResults dispatch calls
- Casting adapter to its concrete type before dispatching requests in Pull
=> Fixing base Adapter correctly calling Read methods on concrete adapters

BHoM_Adapter/AdapterActions/_PushMethods/ExternalId/AssignId.cs
Closes #208 
Removing check if object already has an AdapterId for objects to be created.
See issue for more details, but this means new objects, set to be created, should always get a new id assigned, independent if they had one before or not.
@kThorsager do you have a link to the scripts giving you problems?
- Removing check if AdapterNameId already exists in custom data before assigning fresh id to objects being created.
=> Always assign new ids for objects being created

Adapter_Engine/Adapter_Engine.csproj, Adapter_Engine/Query/AdapterMethods.cs
Closes #211 
Implemented methods as described by #211 .
The main method we are looking for here is [`CRUDcompatibleTypes()`](https://github.com/BHoM/BHoM_Adapter/pull/212/files#diff-aed398b26b0006559b947af68281cdddR85). This returns a `Dictionary<string,  Dictionary<Type, List<MethodInfo>>>`, that has:
- string key, one of: `Create`, `Read`, `Update`, `Delete`;
- value: another Dictionary with:
- key: BHoM Type of with some CRUD method that supports it
- value: list of CRUD methods compatible with that Type.
https://burohappold.sharepoint.com/:f:/s/BHoM/EuyegrQgtQlCvxyFw8L7ikQBkgksD0yYdjYRHA1cx3C9kg?e=A0gdN5
=> Adapter_Engine: extraction of CRUD methods compatible with specific objects types

Adapter_oM/enums/PushType.cs, BHoM_Adapter/AdapterActions/Push.cs, BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
Closes #204 
As stated in Issue, adding additional PushType, working exactly as FUllCRUD, except it does not call Update for the intersection of the venn diagram. Instead only UpdateTags is being called, for obejcts that do contain tags.
General principle: Create stuff not already in the model, leave the rest.
Which is different from the default CRUD: Create stuff not existing, update the rest.
https://burohappold.sharepoint.com/:f:/s/BHoM/EkXvc8ZBXOZNr7HhmSEuzW8BS6e5UN6hCkJMXHCfO2E3Xg?e=lniam2
@JosefTaylor , I think this should resolve https://github.com/BHoM/ETABS_Toolkit/issues/102
=> Add CreateNonExisting push type and methods

Structure_AdapterModules/ErrorMessages/ErrorMessages.cs
Closes #245 
Adds error message for pushing loads with no ids assigned to them.
Message with no name:
Message with name:
To be used by toolkits for better reporting on loads not being able to be pushed due to the objects lacking id information.
=> Add error message for failing pushing of Loads

BHoM_Adapter/BHoMAdapter.cs
Closes #256
As title. Needed for BHoM_UI to correctly link the Event raised from adapters as explained by @adecler
=> BHoM_Adapter: add `NewGuid()` auto-initialiser to AdapterGuid

Adapter_Engine/Query/GetComparerForType.cs, Adapter_oM/Settings-Config/ActionConfig.cs
https://github.com/BHoM/BHoM_Engine/pull/2105
Closes https://github.com/BHoM/BHoM_Adapter/issues/267
=> Align to changes on Diffing

Structure_AdapterModules/CopyNodeProperties.cs, core.txt
Closes #285 
Done is support of https://github.com/BHoM/GSA_Toolkit/pull/225 for example.
Nodes to check if the source node has a set coordinate system while the node being pushed does not. Important if pushing support before meshes/bars for example to keep the pre-set coordinates in the model.
=> Copy orientation support for nodes

Adapter_Engine/Query/AdapterId.cs
Closes #291
the versioning for AdaperId added in PR https://github.com/BHoM/BHoM_Adapter/pull/290 was invalid. This PR fixes that.
Try to input this into a `FromJson` component:
```
{ "_t" : "System.Reflection.MethodBase", "TypeName" : "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.Engine.Adapter.Query, Adapter_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null\" }", "MethodName" : "AdapterId", "Parameters" : ["{ \"_t\" : \"System.Type\", \"Name\" : \"BH.oM.Base.IBHoMObject\" }", "{ \"_t\" : \"System.Type\", \"Name\" : \"System.Type, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\" }"] }
```
This corresponds to the AdapterId method as it was in the last beta.
=> Adapter_Engine: Fix AdapterId versioning

Adapter_Engine/Query/GetComparerForType.cs
https://github.com/BHoM/BHoM_Engine/pull/2652
Closes https://github.com/BHoM/BHoM_Adapter/issues/313
Added a `using` reference to support the `HashComparer` that has been moved to `BH.Engine.Base` from `BH.Engine.Diffing`.
See https://github.com/BHoM/BHoM_Engine/pull/2652
- Added a `using` reference to support the `HashComparer` that has been moved to `BH.Engine.Base` from `BH.Engine.Diffing`.
=> Adapter_Engine: add reference for `HashComparer`

BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs
Closes #326
Fix an incorrect null check on tags. There was no guard against null values.
See https://github.com/BHoM/BHoM_Adapter/issues/326
=> Fix incorrect null check on Tag prior to Push via FullCRUD

.ci/code/BHoM_Adapter_Tests/Objects/StructuralAdapter.cs, .ci/code/BHoM_Adapter_Tests/PushTests.cs, Adapter_oM/Settings-Config/AdapterSettings.cs, BHoM_Adapter/AdapterActions/Pull.cs, BHoM_Adapter/AdapterActions/Push.cs, BHoM_Adapter/AdapterActions/Remove.cs, BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/CreateOnly.cs, BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/FullCRUD.cs, BHoM_Adapter/AdapterActions/_PushMethods/CRUDDispatchers/UpdateOnly.cs, BHoM_Adapter/CRUD/Cache.cs
Closes #336
Add caching system in the base adapter, reducing the times the same objects are read more than once from the model.
Can for some cases significantly speed up both push and pulls from the adapter, depending o the case being run.
For full effect, the concrete adapters need to be updated to make use of this new system.
=> Add caching system for CRUD methods

.ci/code/BHoM_Adapter_Tests/Objects/StructuralAdapter.cs, .ci/code/BHoM_Adapter_Tests/PushTests.cs, Adapter_Engine/Query/GetDependencySortedObjects.cs, Adapter_Engine/Query/GetDependencyTypes.cs
Closes #339
Fixing an issue with the dependency ordering that could occur for some cases where a deeper dependency chain required to be evaluated. Was highlighted when trying to push Bar loads by their own, leading to an error in terms of order where the Bars where pushed before for example Nodes and Sections.
Issue has now been fixed with a tweak to the sorting methodology.
Also, adding a non-generic method for extracting dependency types for a particular type.
Can be validated with new PushTest in verification solution.
Also, pushing a single BarLoad to Robot, while using https://github.com/BHoM/Robot_Toolkit/pull/506 should work.
=> Fix issue with deep dependency types

BHoM_Adapter/AdapterActions/Execute.cs
Closes #207
<details> 
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Archive name="Root">
<items count="1">
<item name="ArchiveVersion" type_name="gh_version" type_code="80">
<Major>0</Major>
<Minor>2</Minor>
<Revision>2</Revision>
</item>
</items>
<chunks count="1">
<chunk name="Clipboard">
<items count="1">
<item name="plugin_version" type_name="gh_version" type_code="80">
<Major>1</Major>
<Minor>0</Minor>
<Revision>7</Revision>
</item>
</items>
<chunks count="5">
<chunk name="DocumentHeader">
<items count="5">
<item name="DocumentID" type_name="gh_guid" type_code="9">3af2bd3f-3481-4c36-86c2-ae08e5a9c947</item>
<item name="Preview" type_name="gh_string" type_code="10">Shaded</item>
<item name="PreviewMeshType" type_name="gh_int32" type_code="3">1</item>
<item …
=> Adding recorderror message to the default Execute method

.ci/unit-tests/BHoM_Adapter_Tests/Objects/StructuralAdapter.cs, .ci/unit-tests/BHoM_Adapter_Tests/PushTests.cs, Adapter_oM/Module/IPushPreProcessModule.cs, BHoM_Adapter/AdapterActions/_PushMethods/ProcessObjectsForPush.cs, Structure_AdapterModules/ModuleLoader.cs, Structure_AdapterModules/PreProcessLoads.cs, Structure_AdapterModules/ReplaceObjectsInLoadsModule.cs
Closes #347 
Closes #348 
- Adding `IPushPreProcessModule` to enable additional pre-processing to be done lastly in the ProcessObjectsBeforePush method
- Add Module of this new type for handling applying objects to loads being pushed at the same time, based on Guid mapping. This can for example help with Bars pushed at the same time as a Bar load, where this can replace the bars on the load with the same bar being pushed independently, and will for this case ensure the same bars are being reffered to in both cases.
Test case added in the test project.
Test case for Robot here:
[Uploading Beam_Cantilever_convertedFromKarambaInternalised.zip…]()
=> Add pre process module for pushing loads

BHoM_Adapter/AdapterActions/_PushMethods/ProcessObjectsForPush.cs
Closes #350
Closes #351
`ProcessObjectsForPush()` now first Unpacks any `IContainer`, then checks for IBHoMObjects.
This allows to wrap any unpacked non-BHoMObject if required; also, it removes non-relevant warning when an IContainer is provided (as `IContainer` does not implement `IBHoMObject`).
See #350
=> `ProcessObjectsForPush()` to first Unpack any `IContainer`, then check for IBHoMObjects

.ci/unit-tests/BHoM_Adapter_Tests/PushTests.cs, Structure_AdapterModules/ReplaceObjectsInLoadsModule.cs
Closes #352
See issue for details
Tests updated to showcase issues
=> Fix replace objects in loads module culling duplicates

.ci/unit-tests/BHoM_Adapter_Tests/Objects/StructuralAdapter.cs, Structure_AdapterModules/GetGravityLoadElementsWithoutID.cs, Structure_AdapterModules/GetLoadElementsWithoutID.cs
Closes #357
Fixes problem with call order of ModuleLoader and setting AdapterIdType. See issue for more details
All unittests should pass after change or calls in the constructor for SA
=> Fix get dependency modules depending on order in constructor

Adapter_oM/Module/ModuleSet.cs
Closes #367
Existing unit tests, existing adapter scripts.
- Removed the `IObject` implementation on `ModuleSet` class, because the adapter modules are not intended to be serializable or used from a front-end.
=> Adapter_oM: Remove IObject implementation on `ModuleSet` class

BHoM_Adapter/AdapterActions/Execute.cs, BHoM_Adapter/AdapterActions/Move.cs, BHoM_Adapter/AdapterActions/Pull.cs, BHoM_Adapter/AdapterActions/Push.cs, BHoM_Adapter/AdapterActions/Remove.cs, BHoM_Adapter/BHoMAdapter.cs
Not directly dependant, but a related BHoM_UI PR uses these new methods, required for testing in the UI. 
https://github.com/BHoM/BHoM_UI/pull/481
Closes #383
Introducing "before" and "after" methods for adapter actions following discussion between @FraserGreenroyd and @alelom.
=> BHoM_Adapter: Adding Before and After methods for each action

Adapter_Engine/Query/GetActiveObject.cs
Closes #397 
[Installer](https://burohappold.sharepoint.com/:f:/s/BHoM/EngdHnX9w_5Jr0c2sk7UwmkBUM7VocNTlrLZjH2NZEYk4A?e=C3wYUz)
As a minimum test for each adapter:
1. Run the adapter in Rhino 8;
2. Push a `Bar`;
3. Run an `Execute` method;
4. Pull a result.
- Added `GetActiveObject` method that calls directly from the DLLs to allow adapters built using .NET Framework to function in .NET Core environments such as Rhino 8.
=> Add GetActiveObject method to allow its use in .NET Core environments

Adapter_oM/ExecuteCommands/Import.cs
Closes #400 
Sets up import as a global execute action.
- Added `ImportFile` execute action for adapters to import supported file types.
=> Add import to the execute actions
